[package]

name = "dice_bot"
version = "0.0.1"
authors = ["subliun <subliunisdev@gmail.com>"]

[dependencies.rstox]

git = "https://github.com/suhr/rstox.git"
branch = "audio"

[dependencies.markov]

git = "https://github.com/aatxe/markov.git"

[dependencies]
time = "*"
